version: 2

sources:
  - name: traders_raw
    database: TRADERS_DB
    schema: RAW

    tables:
      - name: load_customers_traders_north
      - name: load_customers_traders_south
      - name: load_products_traders_north
      - name: load_products_traders_south
      - name: load_employees_traders_north
      - name: load_employees_traders_south